import { useLocale } from "next-intl";

const copy = {
  en: { label: "AI and client data", heading: "Clear boundaries before credentials or client records are involved.", intro: "Every engagement documents what the system can do, where it can fail, which data leaves the client’s tools, and who can reverse or approve an outcome.", items: [["Data minimization", "Use the least client data needed for the workflow and avoid production access during early discovery."], ["Controlled credentials", "Client-owned accounts, scoped permissions, and secrets kept out of interfaces, repositories, and ordinary logs."], ["Human approval", "Consequential changes remain review-first unless a narrower boundary is explicitly tested and approved."], ["Traceable failures", "Exceptions surface with context and an owner instead of silently producing a plausible result."], ["Handoff and recourse", "Documentation explains operation, limitations, monitoring, and how to pause or reverse the workflow."]] },
  fr: { label: "IA et données client", heading: "Des limites claires avant d’impliquer des accès ou dossiers client.", intro: "Chaque mandat documente ce que le système peut faire, où il peut échouer, quelles données quittent les outils du client et qui peut renverser ou approuver un résultat.", items: [["Données minimales", "Utiliser le moins de données client possible et éviter l’accès production durant la découverte initiale."], ["Accès contrôlés", "Comptes appartenant au client, permissions limitées et secrets absents des interfaces, dépôts et journaux ordinaires."], ["Approbation humaine", "Les changements importants restent centrés sur la révision sauf si une limite plus étroite est testée et approuvée."], ["Échecs traçables", "Les exceptions remontent avec leur contexte et un responsable plutôt que de produire silencieusement un résultat plausible."], ["Transfert et recours", "La documentation explique l’opération, les limites, la surveillance et comment mettre le workflow en pause ou le renverser."]] },
};

export default function TrustStatement() {
  const t = copy[useLocale() === "fr" ? "fr" : "en"];
  return <section className="border-y border-border bg-white px-6 py-20 md:py-24" aria-labelledby="trust-heading"><div className="mx-auto max-w-6xl"><div className="grid gap-9 lg:grid-cols-[0.82fr_1.18fr] lg:gap-16"><div><p className="font-mono text-xs uppercase tracking-[0.28em] text-accent">{t.label}</p><h2 id="trust-heading" className="mt-4 font-display text-4xl leading-tight text-cream">{t.heading}</h2><p className="mt-6 leading-7 text-cream-muted">{t.intro}</p></div><dl className="divide-y divide-border border-y border-border">{t.items.map(([term, detail]) => <div className="grid gap-2 py-5 sm:grid-cols-[10rem_1fr]" key={term}><dt className="text-sm font-semibold text-cream">{term}</dt><dd className="text-sm leading-6 text-cream-muted">{detail}</dd></div>)}</dl></div></div></section>;
}
